import type { Profile, EvidenceRecord, Obligation, ShockScenario, Brief } from '../types/database';

export interface DemoProfileData {
  profile: Profile;
  evidence: EvidenceRecord[];
  obligations: Obligation[];
  shockScenarios: ShockScenario[];
  briefs: Brief[];
}

export const DEMO_PROFILES: Record<string, DemoProfileData> = {
  'lakshmi': {
    profile: {
      id: 'demo-user-lakshmi',
      full_name: 'Lakshmi Devi (లక్ష్మీ దేవి / लक्ष्मी देवी)',
      language: 'hi',
      income_type: 'seasonal',
      goal: 'crop_input',
      onboarded: true,
      created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    },
    evidence: [
      {
        id: 'ev-lak-01',
        user_id: 'demo-user-lakshmi',
        type: 'image',
        raw_text: 'PhonePe: Paid ₹45,000 to Lakshmi Devi from AP Mandi Traders for Cotton Harvest. UPI Ref: 334912984102',
        amount: 45000,
        direction: 'in',
        category: 'crop_sale',
        provenance_label: 'verified',
        date: new Date(Date.now() - 12 * 86400000).toISOString().split('T')[0],
        created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
      },
      {
        id: 'ev-lak-02',
        user_id: 'demo-user-lakshmi',
        type: 'image',
        raw_text: 'Google Pay: Received ₹28,000 for Groundnut batch 2. UTR: 99482103941',
        amount: 28000,
        direction: 'in',
        category: 'crop_sale',
        provenance_label: 'verified',
        date: new Date(Date.now() - 35 * 86400000).toISOString().split('T')[0],
        created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
      },
      {
        id: 'ev-lak-03',
        user_id: 'demo-user-lakshmi',
        type: 'manual',
        raw_text: null,
        amount: 8500,
        direction: 'in',
        category: 'wages',
        provenance_label: 'declared',
        date: new Date(Date.now() - 50 * 86400000).toISOString().split('T')[0],
        created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
      },
      {
        id: 'ev-lak-04',
        user_id: 'demo-user-lakshmi',
        type: 'image',
        raw_text: 'Paid ₹12,000 to Sri Balaji Fertilizers. UPI Txn ID 44021948201',
        amount: 12000,
        direction: 'out',
        category: 'crop_sale',
        provenance_label: 'verified',
        date: new Date(Date.now() - 20 * 86400000).toISOString().split('T')[0],
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
      },
      {
        id: 'ev-lak-05',
        user_id: 'demo-user-lakshmi',
        type: 'manual',
        raw_text: null,
        amount: 6500,
        direction: 'out',
        category: 'groceries',
        provenance_label: 'declared',
        date: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0],
        created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
      },
      {
        id: 'ev-lak-06',
        user_id: 'demo-user-lakshmi',
        type: 'manual',
        raw_text: 'Estimated pump electricity & diesel',
        amount: 3200,
        direction: 'out',
        category: 'utility',
        provenance_label: 'estimated',
        date: new Date(Date.now() - 8 * 86400000).toISOString().split('T')[0],
        created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
      },
    ],
    obligations: [
      {
        id: 'ob-lak-01',
        user_id: 'demo-user-lakshmi',
        description: 'Fertilizer supplier seasonal payment',
        due_date: new Date(Date.now() + 18 * 86400000).toISOString().split('T')[0],
        amount: 15000,
        created_at: new Date().toISOString(),
      },
      {
        id: 'ob-lak-02',
        user_id: 'demo-user-lakshmi',
        description: 'Solar irrigation pump installment',
        due_date: new Date(Date.now() + 45 * 86400000).toISOString().split('T')[0],
        amount: 4500,
        created_at: new Date().toISOString(),
      },
    ],
    shockScenarios: [
      {
        id: 'sc-lak-01',
        user_id: 'demo-user-lakshmi',
        scenario_type: 'delayed_payment',
        shock_amount: 20000,
        resulting_shortfall_date: new Date(Date.now() + 65 * 86400000).toISOString().split('T')[0],
        resulting_gap_amount: 3500,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
    ],
    briefs: [
      {
        id: 'br-lak-01',
        user_id: 'demo-user-lakshmi',
        generated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
        expiry_date: new Date(Date.now() + 28 * 86400000).toISOString(),
        revoked: false,
        share_token: 'lakshmi-kisan-2026',
        snapshot_data: {
          generatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
          profileName: 'Lakshmi Devi',
          incomeType: 'seasonal',
          goal: 'crop_input',
          incomeRhythm: 'seasonal',
          bufferDays: 48,
          proofStrength: { verified: 3, declared: 2, estimated: 1, total: 6 },
          goalReadiness: 82,
          totalIncome30d: 45000,
          totalExpenses30d: 21700,
          obligationCount: 2,
          obligationTotal: 19500,
          evidenceCount: 6,
        },
      },
    ],
  },
  'raju': {
    profile: {
      id: 'demo-user-raju',
      full_name: 'Raju Kumar (राजू कुमार)',
      language: 'hi',
      income_type: 'regular-informal',
      goal: 'working_capital',
      onboarded: true,
      created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    },
    evidence: [
      {
        id: 'ev-raj-01',
        user_id: 'demo-user-raju',
        type: 'image',
        raw_text: 'Paytm: Payment from Passenger ₹450. UPI Txn 10928374',
        amount: 450,
        direction: 'in',
        category: 'transport_income',
        provenance_label: 'verified',
        date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
        created_at: new Date().toISOString(),
      },
      {
        id: 'ev-raj-02',
        user_id: 'demo-user-raju',
        type: 'manual',
        raw_text: null,
        amount: 18500,
        direction: 'in',
        category: 'transport_income',
        provenance_label: 'declared',
        date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
        created_at: new Date().toISOString(),
      },
      {
        id: 'ev-raj-03',
        user_id: 'demo-user-raju',
        type: 'manual',
        raw_text: null,
        amount: 4200,
        direction: 'out',
        category: 'utility',
        provenance_label: 'declared',
        date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
        created_at: new Date().toISOString(),
      },
    ],
    obligations: [
      {
        id: 'ob-raj-01',
        user_id: 'demo-user-raju',
        description: 'Auto-rickshaw monthly EMI',
        due_date: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
        amount: 6200,
        created_at: new Date().toISOString(),
      },
    ],
    shockScenarios: [],
    briefs: [],
  },
  'priya': {
    profile: {
      id: 'demo-user-priya',
      full_name: 'Priya Sharma (प्रिया शर्मा)',
      language: 'hi',
      income_type: 'mixed',
      goal: 'education_fee',
      onboarded: true,
      created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    },
    evidence: [
      {
        id: 'ev-pri-01',
        user_id: 'demo-user-priya',
        type: 'image',
        raw_text: 'UPI: Received ₹14,500 from Bridal Boutique for 6 custom stitched dresses. Txn ID: 918230192',
        amount: 14500,
        direction: 'in',
        category: 'shop_sale',
        provenance_label: 'verified',
        date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
        created_at: new Date().toISOString(),
      },
      {
        id: 'ev-pri-02',
        user_id: 'demo-user-priya',
        type: 'image',
        raw_text: 'Paid ₹5,200 for Silk Fabric & Sewing Threads. UPI Ref: 8812039',
        amount: 5200,
        direction: 'out',
        category: 'shop_sale',
        provenance_label: 'verified',
        date: new Date(Date.now() - 8 * 86400000).toISOString().split('T')[0],
        created_at: new Date().toISOString(),
      },
    ],
    obligations: [
      {
        id: 'ob-pri-01',
        user_id: 'demo-user-priya',
        description: 'Daughter school term tuition',
        due_date: new Date(Date.now() + 25 * 86400000).toISOString().split('T')[0],
        amount: 9000,
        created_at: new Date().toISOString(),
      },
    ],
    shockScenarios: [],
    briefs: [],
  },
};
